// This file is auto-generated by scripts/build-registry.ts
// Do not edit this file directly

export const accordionComponents = [
  {
    name: "accordion-box-contained",
  },
  {
    name: "accordion-box",
  },
  {
    name: "accordion-contained",
  },
  {
    name: "accordion-default",
  },
  {
    name: "accordion-disabled-item",
  },
  {
    name: "accordion-expand-icon",
  },
  {
    name: "accordion-highlight-active-item",
  },
  {
    name: "accordion-media-content",
  },
  {
    name: "accordion-multiple-expanded-at-a-time",
  },
  {
    name: "accordion-outline",
  },
  {
    name: "accordion-tabs",
  },
  {
    name: "accordion-with-icon",
  },
];

export const alertComponents = [
  {
    name: "alert-default",
  },
  {
    name: "alert-destructive",
  },
  {
    name: "alert-info",
  },
  {
    name: "alert-soft",
  },
  {
    name: "alert-success",
  },
  {
    name: "alert-warning",
  },
  {
    name: "alert-with-action",
  },
  {
    name: "alert-with-background",
  },
];

export const alertDialogComponents = [
  {
    name: "alert-dialog-default",
  },
  {
    name: "alert-dialog-destructive",
  },
  {
    name: "alert-dialog-info",
  },
  {
    name: "alert-dialog-success",
  },
  {
    name: "alert-dialog-warning",
  },
  {
    name: "alert-dialog-with-footer",
  },
  {
    name: "alert-dialog-with-header",
  },
  {
    name: "alert-dialog-with-icon",
  },
];

export const avatarComponents = [
  {
    name: "avatar-default",
  },
  {
    name: "avatar-group-max",
  },
  {
    name: "avatar-group",
  },
  {
    name: "avatar-hover-card",
  },
  {
    name: "avatar-shape",
  },
  {
    name: "avatar-with-ring",
  },
  {
    name: "avatar-with-status",
  },
  {
    name: "avatar-with-text",
  },
];

export const badgeComponents = [
  {
    name: "badge-default",
  },
  {
    name: "badge-destructive",
  },
  {
    name: "badge-outline",
  },
  {
    name: "badge-rounded",
  },
  {
    name: "badge-secondary",
  },
  {
    name: "badge-soft",
  },
  {
    name: "badge-status",
  },
];

export const breadcrumbComponents = [
  {
    name: "breadcrumb-default",
  },
  {
    name: "breadcrumb-slash",
  },
  {
    name: "breadcrumb-steps",
  },
  {
    name: "breadcrumb-tab-active",
  },
  {
    name: "breadcrumb-with-dropdown",
  },
  {
    name: "breadcrumb-with-icon",
  },
];

export const carouselComponents = [
  {
    name: "carousel-default",
  },
  {
    name: "carousel-multiple-slides",
  },
  {
    name: "carousel-slide-status-2",
  },
  {
    name: "carousel-slide-status",
  },
  {
    name: "carousel-vertical",
  },
  {
    name: "carousel-with-footer",
  },
  {
    name: "carousel-with-pagination",
  },
  {
    name: "carousel-with-progress",
  },
];

export const categories = {
  accordion: accordionComponents,
  alert: alertComponents,
  alertDialog: alertDialogComponents,
  avatar: avatarComponents,
  badge: badgeComponents,
  breadcrumb: breadcrumbComponents,
  carousel: carouselComponents,
};
