// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  demo: {
    ButtonDemo: {
      name: 'ButtonDemo.tsx',
      files: ['components/_demo/button/ButtonDemo.tsx'],
      registry: require(`~/public/registry/demos/ButtonDemo.json`),
      component: React.lazy(() =>
        import('@/components/_demo/button/ButtonDemo').then((module) => ({
          default: module.ButtonDemo,
        })),
      ),
    },
    LeverDemo: {
      name: 'LeverDemo.tsx',
      files: ['components/_demo/lever/LeverDemo.tsx'],
      registry: require(`~/public/registry/demos/LeverDemo.json`),
      component: React.lazy(() =>
        import('@/components/_demo/lever/LeverDemo').then((module) => ({
          default: module.LeverDemo,
        })),
      ),
    },
  },
};