// This file is autogenerated by scripts/build-registry-demos.ts
// Do not edit this file directly.

type RegistryDemoItem = {
  name: string;
  files: string[];
};

type RegistryDemos = RegistryDemoItem[];

const buildDemos = (component: string, demos: string[]): RegistryDemos => {
  return demos.map((demo) => {
    return {
      name: `${demo}`,
      files: [`@/components/_demo/${component}/${demo}.tsx`],
    };
  });
};

export const demos: RegistryDemos = [
  ...buildDemos("button", ["ButtonDemo"]),
  ...buildDemos("lever", ["LeverDemo"]),
]
