/**
 * This script scans all demo components in @/components/_demo directory and generates a index.tsx file
 * The index.tsx file contains metadata about each demo component including:
 * - name: Name of the demo component
 * - files: Array of file paths for the demo
 * - registry: Path to the JSON registry file containing the demo source code
 */

import { existsSync, promises as fs } from 'node:fs';
import path from 'path';
import { rimraf } from 'rimraf';
import { demos } from '@/components/_demo/registry';

async function buildDemos() {
  let index = `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  demo: {`;

  for (const demo of demos) {
    const name = demo.name;
    const componentPath = demo.files[0].replace('@/', '');
    const importPath = demo.files[0].replace('.tsx', '');

    index += `
    ${name}: {
      name: '${name}.tsx',
      files: ['${componentPath}'],
      registry: import(\'~/public/registry/demos/${name}.json\').then(
        (data) => ({
          default: data.default,
        }),
      ),
      component: React.lazy(() =>
        import('${importPath}').then((module) => ({
          default: module.${name},
        })),
      ),
    },`;
  }

  index += `
  },
};`;

  const targetPath = path.join(process.cwd(), 'src', 'components', '_demo');
  if (!existsSync(targetPath)) {
    await fs.mkdir(targetPath, { recursive: true });
  }
  rimraf.sync(path.join(targetPath, 'index.tsx'));
  await fs.writeFile(path.join(targetPath, 'index.tsx'), index, 'utf8');
  console.log('✅ Generated demo index.tsx file');
}

buildDemos();
